
const tables = [
      {
        text: "No",
        value: "index",
        filterable: false,
        label: "No",
        field: "index",
        sortable: false,
        width: "1%",
        class: "head",
        align: "center",
      },
      {
        text: "Nama Rekening",
        value: "nama_rekening",
        label: "Nama Rekening",
        field: "nama_rekening",
        sortable: true,
        width: "10%",
        class: "head",
        align: "start",
      },
      {
        text: "Gender",
        value: "gender",
        label: "Gender",
        field: "gender",
        width: "1%",
        sortable: true,
        class: "head",
        align: "center",
      },
      {
        text: "Tanggal Lahir",
        value: "tanggal_lahir",
        label: "Tanggal Lahir",
        field: "tanggal_lahir",
        sortable: true,
        class: "head",
        align: "center",
      },
      {
        text: "Tipe",
        value: "tipe_id",
        label: "Tipe",
        field: "tipe_id",
        sortable: true,
        class: "head",
        align: "center",
      },
      {
        text: "No ID",
        value: "no_id",
        label: "No ID",
        field: "no_id",
        sortable: true,
        class: "head",
        align: "center",
      },
      {
        text: "No Rekening",
        value: "no_rekening",
        label: "No Rekening",
        field: "no_rekening",
        sortable: true,
        class: "head",
        align: "center",
      },
      {
        text: "CIF",
        value: "cif",
        label: "CIF",
        field: "cif",
        sortable: true,
        class: "head",
        align: "center",
      },
      {
        text: "Nama Perushaan",
        value: "nama_perusahaan",
        label: "Nama Perushaan",
        field: "nama_perusahaan",
        sortable: true,
        width: '80%',
        class: "head",
        align: "center",
      },
      
]
export default tables